#!/usr/bin/env bash
# Display listening TCP/UDP sockets with PID/program name, then UNIX sockets

# Internet sockets (TCP/UDP) — listening only, numeric, show PID/program

sudo ss -lntup

echo
echo "Active UNIX domain sockets (only servers)"
# UNIX domain sockets — listening only, show PID/program
sudo ss -lxp
