#!/usr/bin/env bash
# Display all active IPv4 addresses on this machine, one per line

# -o : one-line per address; -4 : IPv4; "show up" : interfaces actives
# On filtre les interfaces docker/veth/br- pour coller au checker
ip -o -4 addr show up \
  | awk '!/(docker|veth|br-)/ {print $4}' \
  | cut -d/ -f1
